from app.models.user import User
from app.models.role import Role
from app.models.profile import Profile
from app.models.campus import Campus
from app.models.skill import Skill
from app.models.token_blocklist import TokenBlocklist
from app.models.company import Company
from app.models.job import Job
from app.models.job_skill import job_skills
from app.models.job_category import JobCategory
from app.models.job_application import JobApplication