"""Add proposal fields to job applications

Revision ID: 5443d36ca254
Revises: 81a11e2c28a3
Create Date: 2026-09-11 19:27:29.799458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5443d36ca254'
down_revision = '81a11e2c28a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proposed_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('delivery_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_column('delivery_days')
        batch_op.drop_column('proposed_amount')

    # ### end Alembic commands ###
